import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

enum DriverLanguage { english, french, kinyarwanda }

class DriverLanguageService {
  DriverLanguageService._();

  static const String _prefKey = 'driver.dashboard.language';
  static final DriverLanguageService instance = DriverLanguageService._();

  final ValueNotifier<DriverLanguage> languageNotifier =
      ValueNotifier<DriverLanguage>(DriverLanguage.english);

  bool _isInitialized = false;

  Future<void> ensureInitialized() async {
    if (_isInitialized) return;
    final prefs = await SharedPreferences.getInstance();
    final stored = prefs.getString(_prefKey) ?? 'en';
    languageNotifier.value = _fromCode(stored);
    _isInitialized = true;
  }

  Future<void> setLanguage(DriverLanguage language) async {
    languageNotifier.value = language;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_prefKey, codeOf(language));
  }

  String codeOf(DriverLanguage language) {
    switch (language) {
      case DriverLanguage.english:
        return 'en';
      case DriverLanguage.french:
        return 'fr';
      case DriverLanguage.kinyarwanda:
        return 'rw';
    }
  }

  DriverLanguage _fromCode(String code) {
    switch (code.trim().toLowerCase()) {
      case 'fr':
        return DriverLanguage.french;
      case 'rw':
      case 'kinyarwanda':
        return DriverLanguage.kinyarwanda;
      default:
        return DriverLanguage.english;
    }
  }

  String languageLabel(DriverLanguage language) {
    switch (language) {
      case DriverLanguage.english:
        return 'English';
      case DriverLanguage.french:
        return 'Francais';
      case DriverLanguage.kinyarwanda:
        return 'Kinyarwanda';
    }
  }

  String t(String key, {Map<String, String>? args}) {
    final lang = languageNotifier.value;
    final table = _translations[lang] ?? _translations[DriverLanguage.english]!;
    var result =
        table[key] ?? _translations[DriverLanguage.english]![key] ?? key;
    if (args != null) {
      args.forEach((k, v) {
        result = result.replaceAll('{$k}', v);
      });
    }
    return result;
  }

  static final Map<DriverLanguage, Map<String, String>> _translations = {
    DriverLanguage.english: {
      'nav.home': 'Home',
      'nav.requests': 'Requests',
      'nav.earnings': 'Earnings',
      'nav.history': 'History',
      'nav.profile': 'Profile',
      'status.online': 'You are now Online',
      'status.offline': 'You are now Offline',
      'settings.title': 'App Settings',
      'settings.darkMode': 'Dark Mode',
      'settings.notifications': 'Notifications',
      'settings.language': 'Language',
      'settings.location': 'Location Services',
      'settings.changePassword': 'Change password',
      'settings.currentPassword': 'Current password',
      'settings.newPassword': 'New password',
      'settings.confirmPassword': 'Confirm new password',
      'settings.updatePassword': 'Update password',
      'settings.updatingPassword': 'Updating password...',
      'settings.passwordRequired': 'All password fields are required.',
      'settings.passwordLength': 'New password must be at least 6 characters.',
      'settings.passwordMismatch':
          'New password and confirmation do not match.',
      'settings.passwordRelogin': 'Please login again to update password.',
      'settings.passwordUpdated': 'Password updated successfully.',
      'home.welcome': 'Welcome, Driver {name}',
      'home.ready': 'Ready to accept more rides today?',
      'home.online': 'You are Online',
      'home.offline': 'You are Offline',
      'home.onlineHint': 'You can receive ride requests now.',
      'home.offlineHint': 'Turn online to start receiving requests.',
      'home.tripStatus': 'Current Trip Status',
      'home.requests': 'Nearby Ride Requests',
      'home.stats': "Today's Statistics",
      'home.activeTrip': 'Active Trip: {name}',
      'home.completeTrip': 'Complete Trip',
      'home.markOnRoute': 'Mark: On Route',
      'home.markInProgress': 'Mark: In Progress',
      'home.stageUpdate': 'Trip stage updated to {stage}',
      'home.tripCompleted': 'Trip completed for {name}',
      'home.driverLocation': 'Driver Location',
      'home.liveMap': 'Live Map',
      'home.waiting': 'Waiting for ride request',
      'home.offlineState': 'You are offline',
      'home.waitingHint': 'Stay online to get matched with nearby passengers.',
      'home.offlineStateHint': 'Turn online to start navigating to passengers.',
      'timeline.accepted': 'Accepted',
      'timeline.onRoute': 'On Route',
      'timeline.inProgress': 'In Progress',
      'timeline.completed': 'Completed',
      'stats.trips': 'Trips',
      'stats.earnings': 'Earnings',
      'stats.rating': 'Rating',
      'stats.today': 'Today',
      'stats.driverScore': 'Driver Score',
      'requests.title': 'Ride Requests',
      'requests.onlineHint': 'You can accept incoming rides',
      'requests.offlineHint': 'Go online to receive requests',
      'requests.none': 'No new ride requests right now.',
      'requests.offlineTitle': 'You are currently offline',
      'requests.offlineBody':
          'Switch online from Home to receive and accept ride requests.',
      'requests.accepted': 'Ride accepted for {name}',
      'requests.rejected': 'Ride rejected for {name}',
      'requests.expire': 'Auto-expire in {time}',
      'requests.accept': 'Accept',
      'requests.reject': 'Reject',
      'earnings.title': 'Earnings',
      'trips.title': 'Trip History',
      'profile.title': 'Driver Profile',
      'profile.vehicle': 'Vehicle Information',
      'profile.online': 'Driver is Online',
      'profile.offline': 'Driver is Offline',
      'profile.edit': 'Edit Profile',
      'profile.vehicleMenu': 'Vehicle Information',
      'profile.payout': 'Payment & Payout Information',
      'profile.bookings': 'Booking Queue',
      'profile.notifications': 'Notifications',
      'profile.settings': 'App Settings',
      'profile.help': 'Help & Support',
      'profile.logout': 'Logout',
      'logout.confirmTitle': 'Logout',
      'logout.confirmBody': 'Are you sure you want to logout?',
      'common.cancel': 'Cancel',
      'common.yes': 'Yes',
      'common.retry': 'Retry',
      'common.all': 'All',
      'common.unread': 'Unread',
      'common.required': 'Required',
      'common.unknown': 'Unknown',
      'home.errorRequests': 'Failed to load requests. Pull down to retry.',
      'home.errorStats': 'Failed to load stats. Pull down to retry.',
      'home.requestPassenger': 'Passenger',
      'home.requestPickupMissing': 'Pickup not set',
      'home.requestDestinationMissing': 'Destination not set',
      'profile.driverRating': 'Driver Rating: {value}',
      'profile.driverRatingMissing': 'Driver Rating: --',
      'profile.vehicleLabel': 'Vehicle',
      'profile.plateNumber': 'Plate Number',
      'profile.color': 'Color',
      'profile.category': 'Category',
      'trips.empty': 'No trip history available yet.',
      'trips.unknownPickup': 'Unknown pickup',
      'trips.unknownDestination': 'Unknown destination',
      'trips.unknownTime': 'Unknown time',
      'trips.defaultStatus': 'Completed',
      'trips.passengerRating': 'Passenger ★ {value}',
      'trips.passengerRatingMissing': 'Passenger ★ --',
      'earnings.recent': 'Recent Earnings',
      'earnings.emptyRecent': 'No recent earning entries yet.',
      'earnings.today': 'Today',
      'earnings.thisWeek': 'This Week',
      'earnings.thisMonth': 'This Month',
      'earnings.ridesCompleted': '{count} rides completed',
      'earnings.weeklyTotal': 'Weekly total',
      'earnings.monthlyTotal': 'Monthly total',
      'earnings.performanceOverview': 'Performance Overview',
      'earnings.completedRides': 'Completed Rides',
      'earnings.hoursOnline': 'Hours Online',
      'earnings.monthlyGoal': 'Monthly Goal',
      'earnings.ridesCount': '{count} rides',
      'edit.title': 'Edit Profile',
      'edit.profileUpdated': 'Profile updated successfully.',
      'edit.updatePicture': 'Update Profile Picture',
      'edit.fullName': 'Full Name',
      'edit.phoneNumber': 'Phone Number',
      'edit.emailAddress': 'Email Address',
      'edit.enterName': 'Please enter your name',
      'edit.enterPhone': 'Please enter your phone number',
      'edit.validEmail': 'Please enter a valid email',
      'edit.saveChanges': 'Save Changes',
      'vehicle.title': 'Vehicle Information',
      'vehicle.current': 'Current Vehicle',
      'vehicle.name': 'Vehicle Name',
      'vehicle.plate': 'Plate Number',
      'vehicle.color': 'Vehicle Color',
      'vehicle.category': 'Category',
      'vehicle.economy': 'Economy',
      'vehicle.premium': 'Premium',
      'vehicle.comfort': 'Comfort',
      'vehicle.xl': 'XL',
      'vehicle.saved': 'Vehicle details saved.',
      'vehicle.saveChanges': 'Save Changes',
      'payout.title': 'Payment & Payout',
      'payout.earningsAccount': 'Earnings Account',
      'payout.availableBalance': 'Available Balance',
      'payout.thisWeek': 'This Week',
      'payout.pendingPayout': 'Pending Payout',
      'payout.methodTitle': 'Payout Method',
      'payout.paymentMethod': 'Payment Method',
      'payout.mobileMoney': 'Mobile Money',
      'payout.bankAccount': 'Bank Account',
      'payout.accountHolder': 'Account Holder Name',
      'payout.mobileNumber': 'Mobile Number',
      'payout.bankAccountNumber': 'Bank Account Number',
      'payout.addOrUpdate': 'Add / Update Payout Method',
      'payout.updated': 'Payout method updated successfully.',
      'payout.withdrawalTitle': 'Withdrawal',
      'payout.withdrawalHint':
          'Request a transfer to your selected payout method instantly.',
      'payout.requestWithdrawal': 'Request Withdrawal',
      'payout.withdrawalSubmitted': 'Withdrawal request submitted.',
      'help.title': 'Help & Support',
      'help.faq': 'Frequently Asked Questions',
      'help.contact': 'Contact Support',
      'help.callSupport': 'Call Support',
      'help.emailSupport': 'Email Support',
      'help.connectingCall': 'Connecting to support call...',
      'help.openingEmail': 'Opening email support...',
      'help.reportProblem': 'Report a Problem',
      'help.issueSubmitted': 'Issue report submitted.',
      'help.q1': 'How do I receive more trip requests?',
      'help.a1':
          'Keep your driver status online, maintain high ratings, and stay near busy pickup zones.',
      'help.q2': 'When are payouts processed?',
      'help.a2':
          'Payouts are usually processed daily, while instant withdrawals depend on your selected method.',
      'help.q3': 'How can I update my vehicle details?',
      'help.a3':
          'Go to Profile > Vehicle Information and save your updated details.',
      'bookings.title': 'Booking Queue',
      'bookings.empty': 'No booking requests in queue right now.',
      'bookings.confirm': 'Confirm',
      'bookings.cancel': 'Cancel',
      'bookings.confirmed': 'Booking confirmed.',
      'bookings.cancelled': 'Booking cancelled.',
      'bookings.pendingStatus': 'Pending',
      'bookings.confirmedStatus': 'Confirmed',
      'bookings.cancelledStatus': 'Cancelled',
      'notifications.title': 'Notifications',
      'notifications.empty': 'No notifications available right now.',
      'notifications.markAllRead': 'Mark all read',
      'notifications.clearRead': 'Clear read',
      'notifications.clearActioned': 'Clear actioned',
      'notifications.markRead': 'Mark read',
      'notifications.delete': 'Delete',
      'notifications.back': 'Back',
      'notifications.type': 'Type',
      'notifications.passenger': 'Passenger',
      'notifications.phone': 'Phone',
      'notifications.passengerNotifyPending':
          'Action saved. Passenger notification is pending backend delivery.',
      'notifications.requestIdMissing':
          'Request id is missing for this notification.',
      'notifications.bookingIdMissing':
          'Booking id is missing for this notification.',
      'book.seats': 'Seats',
      'trips.pickup': 'Pickup',
      'trips.dropoff': 'Dropoff',
      'request.fare': 'Fare',
    },
    DriverLanguage.french: {
      'nav.home': 'Accueil',
      'nav.requests': 'Demandes',
      'nav.earnings': 'Gains',
      'nav.history': 'Historique',
      'nav.profile': 'Profil',
      'status.online': 'Vous etes maintenant en ligne',
      'status.offline': 'Vous etes maintenant hors ligne',
      'settings.title': 'Parametres',
      'settings.darkMode': 'Mode sombre',
      'settings.notifications': 'Notifications',
      'settings.language': 'Langue',
      'settings.location': 'Services de localisation',
      'settings.changePassword': 'Changer le mot de passe',
      'settings.currentPassword': 'Mot de passe actuel',
      'settings.newPassword': 'Nouveau mot de passe',
      'settings.confirmPassword': 'Confirmer le nouveau mot de passe',
      'settings.updatePassword': 'Mettre a jour le mot de passe',
      'settings.updatingPassword': 'Mise a jour du mot de passe...',
      'settings.passwordRequired':
          'Tous les champs de mot de passe sont obligatoires.',
      'settings.passwordLength':
          'Le nouveau mot de passe doit contenir au moins 6 caracteres.',
      'settings.passwordMismatch':
          'Le nouveau mot de passe et sa confirmation ne correspondent pas.',
      'settings.passwordRelogin':
          'Veuillez vous reconnecter pour mettre a jour le mot de passe.',
      'settings.passwordUpdated': 'Mot de passe mis a jour avec succes.',
      'home.welcome': 'Bienvenue, Chauffeur {name}',
      'home.ready': 'Pret a accepter plus de courses aujourd\'hui ?',
      'home.online': 'Vous etes en ligne',
      'home.offline': 'Vous etes hors ligne',
      'home.onlineHint': 'Vous pouvez recevoir des demandes maintenant.',
      'home.offlineHint': 'Mettez-vous en ligne pour commencer.',
      'home.tripStatus': 'Statut du trajet actuel',
      'home.requests': 'Demandes a proximite',
      'home.stats': 'Statistiques du jour',
      'home.activeTrip': 'Trajet actif : {name}',
      'home.completeTrip': 'Terminer le trajet',
      'home.markOnRoute': 'Marquer : En route',
      'home.markInProgress': 'Marquer : En cours',
      'home.stageUpdate': 'Etape du trajet mise a jour : {stage}',
      'home.tripCompleted': 'Trajet termine pour {name}',
      'home.driverLocation': 'Position du chauffeur',
      'home.liveMap': 'Carte en direct',
      'home.waiting': 'En attente d\'une demande',
      'home.offlineState': 'Vous etes hors ligne',
      'home.waitingHint': 'Restez en ligne pour etre assigne.',
      'home.offlineStateHint': 'Passez en ligne pour commencer.',
      'timeline.accepted': 'Accepte',
      'timeline.onRoute': 'En route',
      'timeline.inProgress': 'En cours',
      'timeline.completed': 'Termine',
      'stats.trips': 'Courses',
      'stats.earnings': 'Gains',
      'stats.rating': 'Note',
      'stats.today': 'Aujourd\'hui',
      'stats.driverScore': 'Score Chauffeur',
      'requests.title': 'Demandes de course',
      'requests.onlineHint': 'Vous pouvez accepter les demandes',
      'requests.offlineHint': 'Passez en ligne pour recevoir des demandes',
      'requests.none': 'Aucune nouvelle demande pour le moment.',
      'requests.offlineTitle': 'Vous etes actuellement hors ligne',
      'requests.offlineBody':
          'Passez en ligne depuis Accueil pour recevoir des demandes.',
      'requests.accepted': 'Course acceptee pour {name}',
      'requests.rejected': 'Course refusee pour {name}',
      'requests.expire': 'Expiration auto dans {time}',
      'requests.accept': 'Accepter',
      'requests.reject': 'Refuser',
      'earnings.title': 'Gains',
      'trips.title': 'Historique des trajets',
      'profile.title': 'Profil Chauffeur',
      'profile.vehicle': 'Informations du vehicule',
      'profile.online': 'Chauffeur en ligne',
      'profile.offline': 'Chauffeur hors ligne',
      'profile.edit': 'Modifier profil',
      'profile.vehicleMenu': 'Informations du vehicule',
      'profile.payout': 'Paiement et versement',
      'profile.bookings': 'File des reservations',
      'profile.notifications': 'Notifications',
      'profile.settings': 'Parametres',
      'profile.help': 'Aide et support',
      'profile.logout': 'Deconnexion',
      'logout.confirmTitle': 'Deconnexion',
      'logout.confirmBody': 'Etes-vous sur de vouloir vous deconnecter ?',
      'common.cancel': 'Annuler',
      'common.yes': 'Oui',
      'common.retry': 'Reessayer',
      'common.all': 'Tous',
      'common.unread': 'Non lus',
      'common.required': 'Requis',
      'common.unknown': 'Inconnu',
      'home.errorRequests':
          'Impossible de charger les demandes. Tirez vers le bas pour reessayer.',
      'home.errorStats':
          'Impossible de charger les statistiques. Tirez vers le bas pour reessayer.',
      'home.requestPassenger': 'Passager',
      'home.requestPickupMissing': 'Point de depart non defini',
      'home.requestDestinationMissing': 'Destination non definie',
      'profile.driverRating': 'Note chauffeur : {value}',
      'profile.driverRatingMissing': 'Note chauffeur : --',
      'profile.vehicleLabel': 'Vehicule',
      'profile.plateNumber': 'Numero de plaque',
      'profile.color': 'Couleur',
      'profile.category': 'Categorie',
      'trips.empty': 'Aucun historique de trajet pour le moment.',
      'trips.unknownPickup': 'Depart inconnu',
      'trips.unknownDestination': 'Destination inconnue',
      'trips.unknownTime': 'Heure inconnue',
      'trips.defaultStatus': 'Termine',
      'trips.passengerRating': 'Passager ★ {value}',
      'trips.passengerRatingMissing': 'Passager ★ --',
      'earnings.recent': 'Gains recents',
      'earnings.emptyRecent': 'Aucune entree de gain recente.',
      'earnings.today': 'Aujourd\'hui',
      'earnings.thisWeek': 'Cette semaine',
      'earnings.thisMonth': 'Ce mois-ci',
      'earnings.ridesCompleted': '{count} courses terminees',
      'earnings.weeklyTotal': 'Total hebdomadaire',
      'earnings.monthlyTotal': 'Total mensuel',
      'earnings.performanceOverview': 'Apercu des performances',
      'earnings.completedRides': 'Courses terminees',
      'earnings.hoursOnline': 'Heures en ligne',
      'earnings.monthlyGoal': 'Objectif mensuel',
      'earnings.ridesCount': '{count} courses',
      'edit.title': 'Modifier profil',
      'edit.profileUpdated': 'Profil mis a jour avec succes.',
      'edit.updatePicture': 'Mettre a jour la photo de profil',
      'edit.fullName': 'Nom complet',
      'edit.phoneNumber': 'Numero de telephone',
      'edit.emailAddress': 'Adresse e-mail',
      'edit.enterName': 'Veuillez entrer votre nom',
      'edit.enterPhone': 'Veuillez entrer votre numero de telephone',
      'edit.validEmail': 'Veuillez entrer un e-mail valide',
      'edit.saveChanges': 'Enregistrer les modifications',
      'vehicle.title': 'Informations du vehicule',
      'vehicle.current': 'Vehicule actuel',
      'vehicle.name': 'Nom du vehicule',
      'vehicle.plate': 'Numero de plaque',
      'vehicle.color': 'Couleur du vehicule',
      'vehicle.category': 'Categorie',
      'vehicle.economy': 'Economique',
      'vehicle.premium': 'Premium',
      'vehicle.comfort': 'Confort',
      'vehicle.xl': 'XL',
      'vehicle.saved': 'Details du vehicule enregistres.',
      'vehicle.saveChanges': 'Enregistrer les modifications',
      'payout.title': 'Paiement et versement',
      'payout.earningsAccount': 'Compte de gains',
      'payout.availableBalance': 'Solde disponible',
      'payout.thisWeek': 'Cette semaine',
      'payout.pendingPayout': 'Versement en attente',
      'payout.methodTitle': 'Methode de versement',
      'payout.paymentMethod': 'Methode de paiement',
      'payout.mobileMoney': 'Mobile Money',
      'payout.bankAccount': 'Compte bancaire',
      'payout.accountHolder': 'Nom du titulaire',
      'payout.mobileNumber': 'Numero mobile',
      'payout.bankAccountNumber': 'Numero de compte bancaire',
      'payout.addOrUpdate': 'Ajouter / Mettre a jour la methode',
      'payout.updated': 'Methode de versement mise a jour.',
      'payout.withdrawalTitle': 'Retrait',
      'payout.withdrawalHint':
          'Demandez un transfert instantane vers votre methode de versement.',
      'payout.requestWithdrawal': 'Demander un retrait',
      'payout.withdrawalSubmitted': 'Demande de retrait envoyee.',
      'help.title': 'Aide et support',
      'help.faq': 'Questions frequentes',
      'help.contact': 'Contacter le support',
      'help.callSupport': 'Appeler le support',
      'help.emailSupport': 'Ecrire au support',
      'help.connectingCall': 'Connexion a l\'appel de support...',
      'help.openingEmail': 'Ouverture du support e-mail...',
      'help.reportProblem': 'Signaler un probleme',
      'help.issueSubmitted': 'Probleme signale avec succes.',
      'help.q1': 'Comment recevoir plus de demandes de trajet ?',
      'help.a1':
          'Gardez votre statut en ligne, maintenez une bonne note, et restez pres des zones actives.',
      'help.q2': 'Quand les versements sont-ils traites ?',
      'help.a2':
          'Les versements sont generalement traites chaque jour; les retraits instantanes dependent de la methode choisie.',
      'help.q3': 'Comment mettre a jour les details du vehicule ?',
      'help.a3':
          'Allez dans Profil > Informations du vehicule et enregistrez vos modifications.',
      'bookings.title': 'File des reservations',
      'bookings.empty':
          'Aucune demande de reservation en attente pour le moment.',
      'bookings.confirm': 'Confirmer',
      'bookings.cancel': 'Annuler',
      'bookings.confirmed': 'Reservation confirmee.',
      'bookings.cancelled': 'Reservation annulee.',
      'bookings.pendingStatus': 'En attente',
      'bookings.confirmedStatus': 'Confirmee',
      'bookings.cancelledStatus': 'Annulee',
      'notifications.title': 'Notifications',
      'notifications.empty': 'Aucune notification disponible pour le moment.',
      'notifications.markAllRead': 'Tout marquer lu',
      'notifications.clearRead': 'Effacer lus',
      'notifications.clearActioned': 'Effacer les notifications traitees',
      'notifications.markRead': 'Marquer comme lu',
      'notifications.delete': 'Supprimer',
      'notifications.back': 'Retour',
      'notifications.type': 'Type',
      'notifications.passenger': 'Passager',
      'notifications.phone': 'Telephone',
      'notifications.passengerNotifyPending':
          'Action enregistree. La notification passager est en attente de livraison backend.',
      'notifications.requestIdMissing':
          'Identifiant de demande manquant pour cette notification.',
      'notifications.bookingIdMissing':
          'Identifiant de reservation manquant pour cette notification.',
      'book.seats': 'Places',
      'trips.pickup': 'Depart',
      'trips.dropoff': 'Destination',
      'request.fare': 'Tarif',
    },
    DriverLanguage.kinyarwanda: {
      'nav.home': 'Ahabanza',
      'nav.requests': 'Ibisabwa',
      'nav.earnings': 'Inyungu',
      'nav.history': 'Amateka',
      'nav.profile': 'Umwirondoro',
      'status.online': 'Ubu uri online',
      'status.offline': 'Ubu uri offline',
      'common.all': 'Byose',
      'common.unread': 'Bitasomwe',
      'settings.title': 'Igenamiterere rya App',
      'settings.darkMode': 'Uburyo bw\'ijoro',
      'settings.notifications': 'Amamenyesha',
      'settings.language': 'Ururimi',
      'settings.location': 'Serivisi z\'ahantu',
      'settings.changePassword': 'Hindura ijambo banga',
      'settings.currentPassword': 'Ijambo banga rya none',
      'settings.newPassword': 'Ijambo banga rishya',
      'settings.confirmPassword': 'Emeza ijambo banga rishya',
      'settings.updatePassword': 'Vugurura ijambo banga',
      'settings.updatingPassword': 'Birimo kuvugurura ijambo banga...',
      'settings.passwordRequired': 'Ibice byose by\'ijambo banga birasabwa.',
      'settings.passwordLength':
          'Ijambo banga rishya rigomba kuba rifite nibura inyuguti 6.',
      'settings.passwordMismatch': 'Ijambo banga rishya n\'iryemeza ntibihura.',
      'settings.passwordRelogin':
          'Injira bundi bushya kugira ngo uvugurure ijambo banga.',
      'settings.passwordUpdated': 'Ijambo banga ryavuguruwe neza.',
      'home.welcome': 'Murakaza neza, Umushoferi {name}',
      'home.ready': 'Witeguye kwakira ingendo nyinshi uyu munsi?',
      'home.online': 'Uri online',
      'home.offline': 'Uri offline',
      'home.onlineHint': 'Ushobora kwakira ibisabwa by\'ingendo ubu.',
      'home.offlineHint': 'Jya online kugira ngo utangire kwakira ibisabwa.',
      'home.tripStatus': 'Imiterere y\'urugendo ruriho',
      'home.requests': 'Ibisabwa biri hafi',
      'home.stats': 'Imibare y\'uyu munsi',
      'home.activeTrip': 'Urugendo ruriho: {name}',
      'home.completeTrip': 'Rangiza urugendo',
      'home.markOnRoute': 'Shyiraho: Mu nzira',
      'home.markInProgress': 'Shyiraho: Ruratangiye',
      'home.stageUpdate': 'Icyiciro cy\'urugendo cyahinduwe: {stage}',
      'home.tripCompleted': 'Urugendo rurangiye kuri {name}',
      'home.driverLocation': 'Aho umushoferi ari',
      'home.liveMap': 'Ikarita iri live',
      'home.waiting': 'Utegereje igisabwa cy\'urugendo',
      'home.offlineState': 'Uri offline',
      'home.waitingHint': 'Komeza online kugira ngo ubone ababagenzi.',
      'home.offlineStateHint': 'Jya online kugira ngo utangire.',
      'timeline.accepted': 'Byakiriwe',
      'timeline.onRoute': 'Mu nzira',
      'timeline.inProgress': 'Bikomeje',
      'timeline.completed': 'Byarangiye',
      'stats.trips': 'Ingendo',
      'stats.earnings': 'Inyungu',
      'stats.rating': 'Amanota',
      'stats.today': 'Uyu munsi',
      'stats.driverScore': 'Amanota y\'umushoferi',
      'requests.title': 'Ibisabwa by\'ingendo',
      'requests.onlineHint': 'Ushobora kwakira ibisabwa byinjira',
      'requests.offlineHint': 'Jya online kugira ngo wakire ibisabwa',
      'requests.none': 'Nta bisabwa bishya bihari ubu.',
      'requests.offlineTitle': 'Ubu uri offline',
      'requests.offlineBody':
          'Jya online muri Ahabanza kugira ngo wakire ibisabwa.',
      'requests.accepted': 'Urugendo rwemejwe kuri {name}',
      'requests.rejected': 'Urugendo rwanzwe kuri {name}',
      'requests.expire': 'Bizarangira mu {time}',
      'requests.accept': 'Emeza',
      'requests.reject': 'Hakana',
      'earnings.title': 'Inyungu',
      'trips.title': 'Amateka y\'ingendo',
      'profile.title': 'Umwirondoro w\'umushoferi',
      'profile.vehicle': 'Amakuru y\'ikinyabiziga',
      'profile.online': 'Umushoferi ari online',
      'profile.offline': 'Umushoferi ari offline',
      'profile.edit': 'Hindura umwirondoro',
      'profile.vehicleMenu': 'Amakuru y\'ikinyabiziga',
      'profile.payout': 'Kwishyura na Payout',
      'profile.bookings': 'Urutonde rw\'ibisabwa byo kubika',
      'profile.notifications': 'Amamenyesha',
      'profile.settings': 'Igenamiterere rya App',
      'profile.help': 'Ubufasha',
      'profile.logout': 'Sohoka',
      'logout.confirmTitle': 'Sohoka',
      'logout.confirmBody': 'Uremeza ko ushaka gusohoka?',
      'common.cancel': 'Hagarika',
      'common.yes': 'Yego',
      'common.retry': 'Ongera ugerageze',
      'common.required': 'Birakenewe',
      'common.unknown': 'Ntibizwi',
      'home.errorRequests':
          'Ntibyashobotse kuzana ibisabwa. Kurura hasi wongere ugerageze.',
      'home.errorStats':
          'Ntibyashobotse kuzana imibare. Kurura hasi wongere ugerageze.',
      'home.requestPassenger': 'Umugenzi',
      'home.requestPickupMissing': 'Aho gufatira ntihashyizweho',
      'home.requestDestinationMissing': 'Aho ujya ntihashyizweho',
      'profile.driverRating': 'Amanota y\'umushoferi: {value}',
      'profile.driverRatingMissing': 'Amanota y\'umushoferi: --',
      'profile.vehicleLabel': 'Ikinyabiziga',
      'profile.plateNumber': 'Nomero y\'icyapa',
      'profile.color': 'Ibara',
      'profile.category': 'Icyiciro',
      'trips.empty': 'Nta mateka y\'ingendo ahari ubu.',
      'trips.unknownPickup': 'Aho gufatira ntihazwi',
      'trips.unknownDestination': 'Aho ujya ntihazwi',
      'trips.unknownTime': 'Igihe ntikizwi',
      'trips.defaultStatus': 'Byarangiye',
      'trips.passengerRating': 'Umugenzi ★ {value}',
      'trips.passengerRatingMissing': 'Umugenzi ★ --',
      'earnings.recent': 'Inyungu ziheruka',
      'earnings.emptyRecent': 'Nta nyandiko z\'inyungu ziheruka zirimo.',
      'earnings.today': 'Uyu munsi',
      'earnings.thisWeek': 'Iki cyumweru',
      'earnings.thisMonth': 'Uku kwezi',
      'earnings.ridesCompleted': '{count} ingendo zarangiye',
      'earnings.weeklyTotal': 'Igiteranyo cy\'icyumweru',
      'earnings.monthlyTotal': 'Igiteranyo cy\'ukwezi',
      'earnings.performanceOverview': 'Incamake y\'imikorere',
      'earnings.completedRides': 'Ingendo zarangiye',
      'earnings.hoursOnline': 'Amasaha online',
      'earnings.monthlyGoal': 'Intego y\'ukwezi',
      'earnings.ridesCount': '{count} ingendo',
      'edit.title': 'Hindura umwirondoro',
      'edit.profileUpdated': 'Umwirondoro wavuguruwe neza.',
      'edit.updatePicture': 'Hindura ifoto y\'umwirondoro',
      'edit.fullName': 'Amazina yuzuye',
      'edit.phoneNumber': 'Numero ya telefone',
      'edit.emailAddress': 'Aderesi ya imeyili',
      'edit.enterName': 'Andika izina ryawe',
      'edit.enterPhone': 'Andika numero ya telefone',
      'edit.validEmail': 'Andika imeyili yemewe',
      'edit.saveChanges': 'Bika impinduka',
      'vehicle.title': 'Amakuru y\'ikinyabiziga',
      'vehicle.current': 'Ikinyabiziga kiriho',
      'vehicle.name': 'Izina ry\'ikinyabiziga',
      'vehicle.plate': 'Nomero y\'icyapa',
      'vehicle.color': 'Ibara ry\'ikinyabiziga',
      'vehicle.category': 'Icyiciro',
      'vehicle.economy': 'Bisanzwe',
      'vehicle.premium': 'Byihariye',
      'vehicle.comfort': 'Byoroheje',
      'vehicle.xl': 'XL',
      'vehicle.saved': 'Amakuru y\'ikinyabiziga yabitswe.',
      'vehicle.saveChanges': 'Bika impinduka',
      'payout.title': 'Kwishyura na Payout',
      'payout.earningsAccount': 'Konti y\'inyungu',
      'payout.availableBalance': 'Amafaranga ahari',
      'payout.thisWeek': 'Iki cyumweru',
      'payout.pendingPayout': 'Payout itegerejwe',
      'payout.methodTitle': 'Uburyo bwa payout',
      'payout.paymentMethod': 'Uburyo bwo kwishyura',
      'payout.mobileMoney': 'Mobile Money',
      'payout.bankAccount': 'Konti ya banki',
      'payout.accountHolder': 'Izina rya nyiri konti',
      'payout.mobileNumber': 'Numero ya mobile',
      'payout.bankAccountNumber': 'Numero ya konti ya banki',
      'payout.addOrUpdate': 'Ongeraho / Hindura uburyo bwa payout',
      'payout.updated': 'Uburyo bwa payout bwavuguruwe neza.',
      'payout.withdrawalTitle': 'Kubikuza',
      'payout.withdrawalHint':
          'Saba kohereza amafaranga ako kanya ku buryo wahisemo.',
      'payout.requestWithdrawal': 'Saba kubikuza',
      'payout.withdrawalSubmitted': 'Gusaba kubikuza byoherejwe.',
      'help.title': 'Ubufasha',
      'help.faq': 'Ibibazo bibazwa kenshi',
      'help.contact': 'Vugana n\'ubufasha',
      'help.callSupport': 'Hamagara ubufasha',
      'help.emailSupport': 'Ohereza imeyili',
      'help.connectingCall': 'Turaguhuza n\'ubufasha kuri telefoni...',
      'help.openingEmail': 'Gufungura ubufasha bwa imeyili...',
      'help.reportProblem': 'Raporo ikibazo',
      'help.issueSubmitted': 'Raporo y\'ikibazo yoherejwe.',
      'help.q1': 'Nakora iki ngo mbone ibisabwa byinshi by\'ingendo?',
      'help.a1':
          'Guma online, ugire amanota meza, kandi wegere ahantu hafatirwa cyane.',
      'help.q2': 'Ni ryari payout zitunganywa?',
      'help.a2':
          'Akenshi payout zitunganywa buri munsi, ariko kubikuza ako kanya biterwa n\'uburyo wahisemo.',
      'help.q3': 'Nabasha nte kuvugurura amakuru y\'ikinyabiziga?',
      'help.a3':
          'Jya muri Profile > Vehicle Information hanyuma ubike impinduka zawe.',
      'bookings.title': 'Urutonde rw\'ibisabwa byo kubika',
      'bookings.empty':
          'Nta bisabwa byo kubika biri ku murongo wo gutegereza ubu.',
      'bookings.confirm': 'Emeza',
      'bookings.cancel': 'Hakana',
      'bookings.confirmed': 'Kubika byemejwe.',
      'bookings.cancelled': 'Kubika byanzwe.',
      'bookings.pendingStatus': 'Birategerejwe',
      'bookings.confirmedStatus': 'Byemejwe',
      'bookings.cancelledStatus': 'Byanzwe',
      'notifications.title': 'Amamenyesha',
      'notifications.empty': 'Nta menyesha rihari ubu.',
      'notifications.markAllRead': 'Shyira byose ku byasomwe',
      'notifications.clearRead': 'Siba ibyasomwe',
      'notifications.clearActioned': 'Siba ibyakozweho',
      'notifications.markRead': 'Shyira ku byasomwe',
      'notifications.delete': 'Siba',
      'notifications.back': 'Subira inyuma',
      'notifications.type': 'Ubwoko',
      'notifications.passenger': 'Umugenzi',
      'notifications.phone': 'Telefone',
      'notifications.passengerNotifyPending':
          'Igikorwa cyabitswe. Ubutumwa bw\'umugenzi buracyategereje koherezwa na backend.',
      'notifications.requestIdMissing':
          'Nta nimero y\'ubusabe iri kuri iri menyesha.',
      'notifications.bookingIdMissing':
          'Nta nimero ya booking iri kuri iri menyesha.',
      'book.seats': 'Intebe',
      'trips.pickup': 'Aho gufatira',
      'trips.dropoff': 'Aho ujya',
      'request.fare': 'Igiciro',
    },
  };
}
